backend:
  name: github
  repo: Denperidge/Projects
  branch: main
  site_domain: projects-denperidge.netlify.app

media_folder: "/"

collections:
  - name: "projects"
    label: "Projects"
    folder: "_projects"
    create: true
    fields:
      - {label: Layout, name: "layout", widget: "hidden", default: "project"}
      - {label: Title, name: "title", widget: "string"}
      - {label: Repo owner, name: "repoowner", widget: "string", default: "Denperidge"}  
      - {label: Repo name, name: "reponame", widget: "string"}
      - {label: Website, name: "website", widget: "string", required: false}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Positive parts", name: "pro", widget: "list"}
      - {label: "Lacking parts", name: "con", widget: "list"}

  - name: "contributions"
    label: "contributions"
    folder: "_contributions"
    create: true
    fields:
      - {label: Title, name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Positive parts", name: "positive", widget: "list"}
      - {label: "Lacking parts", name: "lacking", widget: "list"}
