backend:
  name: github
  repo: Denperidge/Projects
  branch: main
  site_domain: projects-denperidge.netlify.app

media_folder: "/"

collections:
  - name: "tags"
    label: "Tags"
    folder: "_tags"
    create: true
    fields:
      - {label: Title, name: "title", widget: "string"}
      - {label: "Colour", name: "colour", widget: "color"}

  - name: "projects"
    label: "Projects"
    folder: "_projects"
    create: true
    fields:
      - {label: Layout, name: "layout", widget: "hidden", default: "project"}
      - {label: Title, name: "title", widget: "string"}
      - {label: Repo owner, name: "repoowner", widget: "string", default: "Denperidge"}  
      - {label: Repo name, name: "reponame", widget: "string"}
      - {label: Website, name: "website", widget: "string", required: false}
      - {label: "Description", name: "description", widget: "text"}
      - label: "Positive parts"
        name: "pro"
        widget: "list"
        allow_add: true
        summary: '{{ field.description }}'
        field: {label: "Description", name: "description", widget: "text"}
      - label: "Negative parts"
        name: "con"
        widget: "list"
        allow_add: true
        field: {label: "Description", name: "description", widget: "text"}
        summary: '{{ field.description }}'
      - label: "Project tags"
        name: "projecttags"
        widget: "relation"
        collection: "tags"
        search_fields: ["title"]
        multiple: true
        value_field: "tag.*.title"
        display_fields: ["title"]
        required: false

  - name: "contributions"
    label: "Contributions"
    folder: "_contributions"
    create: true
    fields:
      - {label: Title, name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Positive parts", name: "positive", widget: "list"}
      - {label: "Lacking parts", name: "lacking", widget: "list"}
